version: '2.3'

#launch all the containers for the f1tenth simulation
services: 
  #create a rosmaster so that all containers can talk to each other properly
  rosmaster: 
    image: platoon_test
    build: .
    container_name: rosmaster
    command: /bin/bash -c 'source devel/setup.bash && roscore'
    stdin_open: true
    tty: true
#launch the f1tenth container and display the gazebo simulation using nvidia drivers
  f1tenth:
    image: platoon_test
    build: .
    container_name: f1tenth
    runtime: nvidia
    stdin_open: true
    tty: true
    #make sure that this container is started after the rosmaster by using the depends clause
    depends_on:
      - "rosmaster"
    #declare environment variables need to display the GUI applications as well as getting the ros containers to talk to each other
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - "ROS_HOSTNAME=f1tenth"
      - "ROS_MASTER_URI=http://rosmaster:11311" 
    #mount the existing host folders in the Docker container so that we don't have to rebuild the image to compile the source images
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ros-logs:/root/.ros/
      - ./src:/home/catkin_ws/src/
      - gazebo-files:/root/.gazebo/
    command: /bin/bash -c 'source devel/setup.bash && roslaunch race f1_tenth_devel.launch'
  
  # #create a seperate container for the rviz simulations
  end_to_end:
    image: tfros
    build: .
    container_name: end_to_end
    #allow the container to make use of the GPU
    runtime: nvidia
    #declare which containers rviz depends on
    depends_on:
      - "rosmaster"
      - "f1tenth"
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - "ROS_HOSTNAME=end_to_end"
      - "ROS_MASTER_URI=http://rosmaster:11311"
    #most of the rviz stuff depends on the f110-fall-2018 skeletons stuff so mount that volume   
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ros-logs:/root/.ros/
      - ./src:/home/catkin_ws/src/
      - gazebo-files:/root/.gazebo/
    command: /bin/bash -c 'source devel/setup.bash && roslaunch race end_to_end.launch'
      
#declare names for the gazebo log files and ros log files which will be handled by docker
volumes:
  ros-logs:
  gazebo-files: