version: '2.3'

#launch all the containers for the f1tenth simulation
services: 
  #create a rosmaster so that all containers can talk to each other properly
  rosmaster: 
    image: platoon
    build: .
    container_name: rosmaster
    command: /bin/bash -c 'source /opt/ros/kinetic/setup.bash && roscore'
    stdin_open: true
    tty: true
#launch the f1tenth container and display the gazebo simulation using nvidia drivers
  f1tenth:
    image: platoon
    build: .
    user: $USER
    container_name: f1tenth
    runtime: nvidia
    stdin_open: true
    tty: true
    #make sure that this container is started after the rosmaster by using the depends clause
    depends_on:
      - "rosmaster"
    #declare environment variables need to display the GUI applications as well as getting the ros containers to talk to each other
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - "ROS_HOSTNAME=f1tenth"
      - "ROS_MASTER_URI=http://rosmaster:11311" 
    #mount the existing host folders in the Docker container so that we don't have to rebuild the image to compile the source images
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /share-docker:/share-docker
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - ros-logs:/root/.ros/
      - /home/$USER:/home/$USER
    command: /bin/bash -c 'source /opt/ros/kinetic/setup.bash && source devel/setup.bash && roslaunch race test.launch gui:=false' 
      
#declare names for the gazebo log files and ros log files which will be handled by docker
volumes:
  ros-logs:
  gazebo-files: